---
- name: update the system && install packages
  hosts: all
  become: yes
  tasks:
  - name: update apt repo & cache
    apt: update_cache=yes force_apt_get=yes cache_valid_time=3600 upgrade=dist
  - name: install docker.io
    apt: 
      name:
      - python3
      - pip
      - docker.io
      - curl
      - net-tools
      - nginx
  - name: making some alias
    ansible.builtin.blockinfile:
      path: /etc/bash.bashrc
      block: |
        alias c=clear
        alias k=kubectl      
  - name: Download kubectl & minikube
    get_url:
      url: https://dl.k8s.io/release/v1.27.4/bin/linux/amd64/kubectl
      dest: /usr/local/bin/kubectl
      mode: +x
    register: download_result      
  - name: output the register variable value  
    debug:
      msg: 
      - "the download_result register of downloading the kubectl =  {{download_result}} "
  - name: Install minikube .deb package from the internet
    ansible.builtin.apt:
      deb: https://storage.googleapis.com/minikube/releases/latest/minikube_latest_amd64.deb

  # - name: Download minikube
  #   get_url:
  #     url: https://storage.googleapis.com/minikube/releases/latest/minikube_latest_amd64.deb
  #     dest: /root
  #     # mode: +x   
  # - name: Install a .deb package
  #   ansible.builtin.apt:
  #     deb: /root/minikube_latest_amd64.deb  
  # - name: dpkg minikube
  #     shell: install /root/     

  - name: start docker 
    systemd: 
      name: docker 
      state: started
      enabled: true
  - name: start nginx 
    systemd: 
      name: nginx
      state: started   
      enabled: true   
  - name: Add ubuntu to docker group
    user: 
      name: ubuntu
      groups: docker 
      append: yes
  - name: Reconnect to server session
    meta: reset_connection
  - name: start minikube as ubuntu user
    ansible.builtin.command: 
    become: yes
    become_user: ubuntu
    args:
      cmd: minikube start --apiserver-ips=13.49.18.9
  - name: configure reverse proxy by nginx
    ansible.builtin.blockinfile:
      path: /etc/nginx/nginx.conf
      block: |
        stream {
          server {
            listen 0.0.0.0:51999;
            #TCP traffic will be forwarded to the specified server
            proxy_pass 192.168.49.2:8443;
          }
        }
  - name: Reload service nginx
    ansible.builtin.systemd:
      name: nginx
      state: restarted   

  - name: Check if .kube/config exists
    ansible.builtin.stat:
      path: /home/ubuntu/.kube/config.original 
    register: stat_result  
  - name: Buckup the native kubeconfig file once and for all
    copy:
      src:  /home/ubuntu/.kube/config
      dest: /home/ubuntu/.kube/config.original
      remote_src: true
    when: not stat_result.stat.exists

  - name: do the encode ca.crt
    shell: 'cat /home/ubuntu/.minikube/ca.crt | /usr/bin/base64 | tr -d "\n" '
    register: bvalue_ca_crt
  - name: output the register variable 
    debug:
      msg: 
      - "the register value of the encoding =  {{bvalue_ca_crt}} "
  - name: modifing the kubeconfig file  
    lineinfile: 
      path: /home/ubuntu/.kube/config
      regexp: '^    certificate-authority: /home/ubuntu/.minikube/ca.crt'
      line: '    certificate-authority-data: {{bvalue_ca_crt.stdout}}'
 
  - name: do the encode user.crt
    shell: 'cat /home/ubuntu/.minikube/profiles/minikube/client.crt | /usr/bin/base64 | tr -d "\n" '
    register: bvalue_user_crt
  - name: output the register variable 
    debug:
      msg: 
      - "the register value of the encoding =  {{bvalue_user_crt}} "
  - name: modifing the kubeconfig file  
    lineinfile: 
      path: /home/ubuntu/.kube/config
      regexp: '^    client-certificate: /home/ubuntu/.minikube/profiles/minikube/client.crt'
      line: '    client-certificate-data: {{bvalue_user_crt.stdout}}'
 
  - name: do the encode user.key
    shell: 'cat /home/ubuntu/.minikube/profiles/minikube/client.key | /usr/bin/base64 | tr -d "\n" '
    register: bvalue_user_key
  - name: output the register variable 
    debug:
      msg: 
      - "the register value of the encoding =  {{bvalue_user_key}} "
  - name: modifing the kubeconfig file  
    lineinfile: 
      path: /home/ubuntu/.kube/config
      regexp: '^    client-key: /home/ubuntu/.minikube/profiles/minikube/client.key'
      line: '    client-key-data: {{bvalue_user_key.stdout}}'

  - name: create our host kubeconfig 
    copy:
      src:  /home/ubuntu/.kube/config
      dest: /home/ubuntu/.kube/config.host
      remote_src: true
  - name: modifing the host kubeconfig   
    lineinfile: 
      path: /home/ubuntu/.kube/config.host
      regexp: '^    server: https://192.168.49.2:8443'
      line: '    server: https://13.49.18.9:51999'
 


# After that --> Just adjust the kube-config file man